### ISSUE TITLE
Installation Issue | failed to run custom build command for `sixel-sys v0.3.1`

### ISSUE THREAD

**Issue by niv-dev** [Siriusmart/youtube-tui#12]
Getting the following error on Windows: 

```
...
   Compiling tracing v0.1.37
   Compiling http-body v0.4.5
   Compiling unicode-normalization v0.1.22
error: failed to run custom build command for `sixel-sys v0.3.1`

Caused by:
  process didn't exit successfully: `C:\Users\hp\AppData\Local\Temp\cargo-installKvraMG\release\build\sixel-sys-d27a964655ef64b9\build-script-build` (exit code: 101)
  --- stdout
  cargo:rustc-link-lib=dylib=sixel
  cargo:rustc-link-search=native=C:\Users\hp\AppData\Local\Temp\cargo-installKvraMG\release\build\sixel-sys-486666fb75208720\out\lib

  --- stderr
  thread 'main' panicked at 'Failed to execute ./configure: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', C:\Users\hp\.cargo\registry\src\github.com-1ecc6299db9ec823\sixel-sys-0.3.1\build.rs:71:22
```

**Comment by Siriusmart** [comment]
I believe that's because libsixels is a linux thing and is not available on windows

try installing again with one of the 2 commands, ive it so that those can be opt-out

```sh
cargo install --git 'https://github.com/siriusmart/youtube-tui' --no-default-features -F 'halfblock' # with image support
cargo install --git 'https://github.com/siriusmart/youtube-tui' --no-default-features # no image support
```

see if it works

**Comment by niv-dev** [comment]
Thanks, installation works perfectly using the second command, however, I'm still getting this error whenever I type in `youtube-tui:`

`Error: Os { code: 87, kind: InvalidInput, message: "The parameter is incorrect." }`

**Comment by Siriusmart** [comment]
I believe its got something to do with the windows file system, but i couldn't get rust running on my windows installation and the code seems fine, therefore i will not be able to fix this issue for now.

now im trying to get a windows 10 VM because the actual physical installation is kinda screwed, but this TUI is not really meant for windows anyways, so if you still want to use it you can run it inside [windows subsystems for linux](https://learn.microsoft.com/en-us/windows/wsl/install) if its fine
