### ISSUE TITLE
uberzug support?

### ISSUE THREAD

**Issue by se7en-x230** [Siriusmart/youtube-tui#13]
Are there plans to support ueberzug? 
Or how to set the thumbnail quality to a better quality?

**Comment by se7en-x230** [comment]
I see it's st terminal that makes trouble. 
Nice program but I am not installing half kde to use konsole

**Comment by Siriusmart** [comment]
+ watch news about [uberzug](https://odysee.com/@BrodieRobertson:5/this-open-source-developer-just-deleted:4)

**Comment by se7en-x230** [comment]
It is showing but blocky which is a st terminal problem.

Yes I did hear that the developer stopped the ueberzug project. Let's hope someone will fork it and continue.

**Comment by Siriusmart** [comment]
heres a for of st that has sixels support, but u might be able to apply some patches urself or idk
https://github.com/galatolofederico/st-sixel

anyways imma close the issue

**Comment by se7en-x230** [comment]
Something strange is going on.

I installed alacrity-sixel and img2sixel works fine
![image](https://user-images.githubusercontent.com/69777713/204078556-b8549b0b-4c0e-4978-a3c8-ab8b0a31548e.png)

in youtube-tui it just looks the same as in st
![image](https://user-images.githubusercontent.com/69777713/204078581-7ab88c3c-16d4-48bd-99e2-ff2ee6f538dc.png)

**Comment by Siriusmart** [comment]
I honestly don't know, ive installed alacritty-sixel and it doesnt work at all. and it doesnt seem to be an issue of the tui, because launching it twice doesnt make loose sixels support

but here's might be what has happened:
- u got both alacritty and alacritty-sixel installed
- u launched alacritty-sixel and it worked just fine
- u then launch alacritty (no sixels) with the command and sixels doesnt work

or launching alacritty with -e removes sixel support, which youtube-tui will fallback to using halfblocks (the blocky display u see)

but honestly thats probably beyond the scope of this program, but if u got time and it rly matters try doing the same thing but with [*this crate*](https://crates.io/crates/viu), which has the same image display as youtube-tui

anyways imma keep this issue closed for now as it doesn't seem to be an issue of the tui

**Comment by se7en-x230** [comment]
I do not have alacritty installed only alacritty-sixel and the screeshots are made out of the same alacratty launch.
img2sixel shows that it has sixel support but for whatever reason doesn't pick it up in youtube-tui.

Only terminal I get it working flawless is konsole and kitty.

**Comment by Siriusmart** [comment]
> or launching alacritty with -e removes sixel support, which youtube-tui will fallback to using halfblocks (the blocky display u see)

honestly its prob the issue for that fork
