### ISSUE TITLE
support for other languages

### ISSUE THREAD

**Issue by justchokingaround** [Siriusmart/youtube-tui#14]
![image](https://user-images.githubusercontent.com/44473782/203298140-a328d9e1-79e1-4ee1-8594-fd1085b4f28b.png)

For instance, russian characters don't render properly, and the program panicks when the user tries to input non english characters in the search query

**Comment by justchokingaround** [comment]
the language displays just fine after video selection, it's just problematic when looking up something

**Comment by Siriusmart** [comment]
A few questions:

1. Does the program exit or does it just freaks out?
2. Which terminal emulator are you using?
3. Does it still happens after setting `images` to `None` in `~/.config/youtube-tui/main.yml`?

Because characters are difficult in Rust, especially in languages where you got multiple characters somehow merges into another character.

**Comment by justchokingaround** [comment]
1. panicks and exits
2. foot, but same behavior on alacritty and kitty
3. yes

sorry for the very late response, love your project and i really appreciate the effort you put into it

**Comment by artamudo** [comment]
Same issue. There's problem in tui-additions.

![image](https://user-images.githubusercontent.com/68419600/204246514-6c8e80a1-a0b7-490e-b986-e1c1ccf79f7d.png)

**Comment by Siriusmart** [comment]
check updated version, this should be fixed

**Comment by justchokingaround** [comment]
can confirm it works, ty :+1:

**Comment by artamudo** [comment]
Now i can write cyrillic letters, but in selection menu they didn't showed. In menu sections it is.

![image](https://user-images.githubusercontent.com/68419600/204375908-23cf2aa4-df63-49e0-9acb-86677d8ed5fe.png)

**Comment by Siriusmart** [comment]
That is because `allow_unicode` is `false` in [main.yml](https://siriusmart.github.io/youtube-tui/config/main.html)

There used to be an issue with the text list displaying unicode, but now it doesnt seem to exist anymore and unicode is enabled by default

alternatively you can *delete config files to regenerate them*

**Comment by artamudo** [comment]
That's works. Thank you to much :) It's the best youtube ncurses client!

**Comment by artamudo** [comment]
Only one problem remains.

![image](https://user-images.githubusercontent.com/68419600/204379669-ae729492-35fa-4b44-9e04-1c980c7ed4c4.png)
 
It's showing when open any live streams.

**Comment by Siriusmart** [comment]
that seems to be a problem on the invidious crate, gonna fix it when i have time

**Comment by Siriusmart** [comment]
created [this issue](https://github.com/Siriusmart/youtube-tui/issues/16) for this
