### ISSUE TITLE
previews on readme

### ISSUE THREAD

**Issue by Dworv** [Siriusmart/youtube-tui#15]
I wanna see what it looks like on the readme.

**Comment by Siriusmart** [comment]
i copied the readme from the [*docs*](https://siriusmart.github.io/youtube-tui/) but i forgot to change the image path from `./images/file.png` to `./docs/src/image/file.png`, gonna make it so that docs uses the main readme instead of its separate copy.

not worth a git commit if its just a readme imo

hi btw
