### ISSUE TITLE
Can't View Channel Videos

### ISSUE THREAD

**Issue by enron-hubbard** [Siriusmart/youtube-tui#20]
When opening a channel, there are three options: Main, Videos, and Playlists. Main & Playlists have expected behavior, but when selecting Videos, the application returns the following:
```
invalid type: map, expected a sequence
```
and no videos are listed.

Environment: manjaro-sway
Rust version: 1.66.1

**Comment by Siriusmart** [comment]
This doesn't seem to be an issue of the TUI. Instead, I think it's a problem at Invidious' end (aka they are returning bad json).

This can be fixed by changing into [one of these](https://api.invidious.io/) Invidious instance in `main.yml`, just note that [yewtu.be](https://yewtu.be/) has api disabled, and [vid.puffyan.us](https://vid.puffyan.us/) is default.

I feel like that there are inconsistencies between different instances, they sometimes "just changes" for no reason, so it's about finding an instance that works for you, and also expect things to break once in a while.

Just to show you how inconsistent things are, [vid.puffyan.us](https://vid.puffyan.us) which wasn't working a while ago is now working again

**Comment by enron-hubbard** [comment]
Okay, that makes sense - I switched to a different Invidious instance and that solved it. Thanks!
