### ISSUE TITLE
Pleasantly surprised to find this gem!

### ISSUE THREAD

**Issue by idlip** [Siriusmart/youtube-tui#29]
This feels so good for terminal lovers and minimalists.

I'm surprised it is not known, it has 7 version and get has few attraction, I see that you have posted on reddit tho has acquired less attention.

Tbh IMO, i can see it replacing [ytfzf](https://github.com/pystardust/ytfzf).

This tool needs more attention!

Thank you dev for making this possible ;)

**Comment by Siriusmart** [comment]
Thanks, I originally made this for a more usable ytfzf alternative to post of r/unixporn.

I didn't post much about this on reddit as it is missing a feature or two, say subscriptions and running blocking commands (the second is done on github but idk why i didnt push it to crates.io)

**Comment by idlip** [comment]
I encountered a weird issue, If i have read-only (#o444) config (yml) file, youtube-tui gives me an weird error.
I do it because that is how i manage my dotfiles via org-mode tangle.

Also with this, it breaks the shell prompt and there is misalignment.

https://0x0.st/HPrL.png

**Comment by Siriusmart** [comment]
Ok here's what's happening.
1. App launches, attempting to load the config files.
2. So how it loads the config is that it reads the file, then it writes to the file using default formatting, adding new options and stuff.
3. Here it fails to write to the config files, so it just decide to not load the config file at all.
4. Because of bad coding, it didn't see any problems with not loading config files.
5. Now the TUI starts, and tries to get the config file contents, its not there and so it panics.
6. And then your terminal gets screwed up because the restore terminal function is not ran, it just exits.

You cannot fix this problem by editing config files, as they are not read in the first place, so just wait for an update.

Also, the command for help is `youtube-tui help`, running `youtube-tui [anything else]` will just replace the default [launch command](https://siriusmart.github.io/youtube-tui/config/commands.html)

**Comment by Siriusmart** [comment]
also another thing, i dont really understand orgmode tangle and stuff, but how do you get the config files in the first place if the program dont have write permission?

**Comment by idlip** [comment]
Ah nice, thanks for quick reply on this!

Org-mode is a different story, Its something like "literate config" where i have source code blocks and documenting texts.
When i execute "tangle" it puts every source code block to the file i mention.

So my flow, is I have single org file to manage all my dotfiles.

Maybe you can direct writing some config to some location/file, say "saved.yml"
No need to force on this, let it work as it seems best.

I see that i can expand this program like scripting with `env` in main.yml and run commands.yml

Surely this can go very extensible.

Thank you, as I said earlier, Man oh Man, this needs more attention. Its super fast and works as expected!

**Comment by Siriusmart** [comment]
I went for the same approach, added a new option saying how config files should be loaded [here](https://siriusmart.github.io/youtube-tui/config/main.html#write_config), as well as a few stacked changes not pushed to crates.io.

I tested it on some read only config files, see if it works on ur machine

(also having a stroke staring at code ive not touched for a few months)

**Comment by idlip** [comment]
Hahaaa, You need to share this again to r/unixporn and r/commandline and even r/linux.
This deserves more appreciation!

You did it very quickly, Cheers ;)

(I have informed bugswriter about this tool, Should see if he can do a shout out on YT)

**Comment by Siriusmart** [comment]
oh ok, ty again
