### ISSUE TITLE
does this  have a youtube live chat feature?

### ISSUE THREAD

**Issue by noelcurray** [Siriusmart/youtube-tui#39]

**Comment by Siriusmart** [comment]
no, this uses the invidious api instead of the official one, so no live chat feature.

moreover, the invidious api does not support logging in using logging in with an youtube account, so you wouldnt be able to send message anyways

but you may be able to add live chat into mpv, [this](https://github.com/BanchouBoo/mpv-youtube-chat) could be what youre looking for (not tested if it works)
