### ISSUE TITLE
Cannot install on mac m2

### ISSUE THREAD

**Issue by ahmad-reza619** [Siriusmart/youtube-tui#43]
![Screenshot 2023-11-08 at 09 21 19](https://github.com/Siriusmart/youtube-tui/assets/52902060/66b905df-8987-4984-a1d5-7aecea009f3e)
above is the screenshot of the error message when i do cargo install youtube-tui

**Comment by Siriusmart** [comment]
the error message says that the `sixels` library is not present in your system, fyi it is used to display images in terminal.

if you don't want sixels you can do the followings:
- Install without sixels: use halfblocks to display pixelated image: `cargo install --no-default-features -F halfblock -F clipboard -F mpv`
- Install without any image capabilities: `cargo install --no-default-features F clipboard -F mpv`

since you're on a mac you might encounter more errors and stuff, i'm leaving this issue open

gl

**Comment by ahmad-reza619** [comment]
I think you meant this command
```bash
cargo install youtube-tui --no-default-features -F halfblock -F clipboard -F mpv
```
just leaving it here if someone encounter the same thing.

Anyway, how do i install sixel in mac tho? i tried to install [libsixel](https://formulae.brew.sh/formula/libsixel#default) and [lsix](https://formulae.brew.sh/formula/lsix#default) from brew but it's not working. so i tried your suggested command, but now i got another error saying [mpv](https://formulae.brew.sh/formula/mpv#default) is not found, so i tried to install it too via homebrew. but it still does not work

idk what to do now

**Comment by Siriusmart** [comment]
- Did you successfully install mpv?
- Try `cargo install --git https://github.com/Siriusmart/youtube-tui --no-default-features -F halfblock -F clipboard -F mpv`, I know it sounds stupid but the mpv the crates.io version tries to link to is 2 years old and somehow work for ubuntu. The git version works on bleeding edge Arch
- Otherwise it could be something wrong with mpv, you can even give that up by installing it without `-F mpv`, note that you will then have to change up the config in commands.yml as you would have disable the embedded mpv player which is huge QoL and the default settings depends on that.
- Or even better: https://asahilinux.org/

**Comment by ahmad-reza619** [comment]
Turns out i was using the wrong one. i should've installed the mpv cask, not formulae 😅 
So i tried to install the cask but still getting the same issue. From browsing the issue i found out that the issue is probably related to https://github.com/Homebrew/homebrew-core/issues/126368. 
So i followed instruction from this issue https://github.com/deus0ww/homebrew-tap/issues/9 but still no luck

I'll just post this here for future references. I'll comeback later to try if i have time. Thanks @Siriusmart for helping out 😄 
(Installing asahi linux seems cool, but it's such an over the top solution for this lol)
