### ISSUE TITLE
Feature request: MPRIS support

### ISSUE THREAD

**Issue by aanderse** [Siriusmart/youtube-tui#45]
What a great program. Any chance we could get [MPRIS](https://specifications.freedesktop.org/mpris-spec/2.2/) support?

**Comment by Siriusmart** [comment]
Since youtube-tui uses mpv internally, it would be possible to take advantage of preexisting mpv scripts.

For example, I use this plugin called [mpv-discord](https://github.com/tnychn/mpv-discord) to tell everyone that I am not an average spotify user, I would just install the plugin and load it by adding `mpv load-script /etc/mpv/scripts/discord.lua` to the end of my launch command in `~/.config/youtube-tui/commands.yml`.

There are multiple mpv mpris plugins available, and I assume that the setup process is similar to how I setup mpv-discord.

**Comment by aanderse** [comment]
I'm not familiar with the `mpv load-script` syntax you provided. When I ran `mpv --script /path/to/mpris/plugin.so $url` the media showed up in my MPRIS client, but when I tried what you suggested it did not.

Is this what you meant?

```console
$ cat ~/.config/youtube-tui/commands.yml
launch_command: loadpage library ;; flush ;; history clear ;; key Esc 0 ;; key Up 0 ;; key Up 0 ;; key Left 0 ;; key Enter 0 ;; mpv load-script /path/to/mpris/plugin.so
```

Thank you for your help!

**Comment by Siriusmart** [comment]
https://github.com/Siriusmart/youtube-tui/assets/71584876/f79c32a2-2956-4442-bf4c-d34f352c87f9

Since I use arch (btw), mpv-mpris installs to /etc/mpv/scripts/mpris.so by default. As shown in the video i was able to get it working

If you want to try and see what went wrong, you can run commands while running the tui by pressing `:` and entering the command u want to do. If the command ran without output then ur proabably good to go, or else if u get -4 exit code something bad happened, if its -12 then its file not found.

**Comment by aanderse** [comment]
Thanks for the help.

Interesting... the MPRIS plugin doesn't work when I play a video for the first time, though it does work after I either play another video, or pause the first video, etc...
