### ISSUE TITLE
How to sign in? 

### ISSUE THREAD

**Issue by BigLadDylan** [Siriusmart/youtube-tui#49]
Maybe I'm missing something but great work on the project but how do I sign in so i can view my personal recommendations?

**Comment by Siriusmart** [comment]
this TUI is based on [invidious](https://invidious.io/), which is an alternative API to youtube for fetching video info and those sort of stuff.

since it is not the api from google, you cannot sign in to your google account, with the benefit of not requiring a user token to use the TUI.

if you are really using it as your primary youtube client, just add the channel to feed so u get the videos you would actually watch

**Comment by BigLadDylan** [comment]
Thats interesting, thanks for the reply.

Do you mean that it isn't intended to be used as a primary youtube client?

If so then what is it intended to be used for?

**Comment by ryanmusante** [comment]
This is perfect to run in kitty terminal split with multiple windows. This is a replacement for an unnecessary gui app

**Comment by Siriusmart** [comment]
> Do you mean that it isn't intended to be used as a primary youtube client?

It *was* intended to be my main client, but then I got into making youtube videos and I now cannot use it as my main client.

> If so then what is it intended to be used for?

It was my main client, now i'm only using it as an offline music player
