### ISSUE TITLE
Getting error "Invalid Request: This helps protect our community. Learn more"

### ISSUE THREAD

**Issue by Saithe6** [Siriusmart/youtube-tui#57]
It happens specifically when trying to open a video from the search bar, and I'm not sure if this is a youtube-tui issue or an issue with youtube spam filters or something similar. What's strange to me tho is that I can click on and watch videos from my subscriptions, bookmarks, and history but just not the search bar. I can open channels from the search bar, tho I frequently get the error "Error: IO error". All this seems to have started recently, within the past few days. I know it's being rewritten so i don't expect these issues to get fixed, moreso I'm reporting them so they might be fixed in the rewrite.

Edit: I forgot to add this to the original post but I can't open videos from the channel  page either, even if I'm subscribed.

Edit 2: Major update, it seems that I can only open videos I've watched in the past, regardless of where I open it from, so it seems likely that it's a youtube anti spam feature of some sort that's preventing third party access to the videos

Edit 3: https://github.com/iv-org/invidious/issues/4734 I found this issue being talked about on the invidious github, seems to be a youtube thing

**Comment by Siriusmart** [comment]
Most problems that users face can be trace back to the invidous-youtube war, and I don't really have a say on how upstream do their stuff. When that happens [changing the instance](https://siriusmart.github.io/youtube-tui/config/main.html) may help.

As for why you can open videos you've watched in the past, it is because the latest 50 video info are cached in history.
